export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_ROLE = 'SET_ROLE';
export const SET_USER = 'SET_USER';
export const SET_ID = 'SET_ID';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const UPDATE_USER_ROLE_REQUEST = 'UPDATE_USER_ROLE_REQUEST';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const UPDATE_USER_ROLE_FAILURE = 'UPDATE_USER_ROLE_FAILURE';
export const CHECK_EMAIL = 'CHECK_EMAIL';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAILURE = 'CHECK_EMAIL_FAILURE';



//GET COURSES
export const FETCH_ENROLLED_COURSES_REQUEST = "FETCH_ENROLLED_COURSES_REQUEST";
export const FETCH_ENROLLED_COURSES_SUCCESS = "FETCH_ENROLLED_COURSES_SUCCESS";
export const FETCH_ENROLLED_COURSES_FAILURE = "FETCH_ENROLLED_COURSES_FAILURE";
export const FETCH_ALL_COURSES_REQUEST = "FETCH_ALL_COURSES_REQUEST";
export const FETCH_ALL_COURSES_SUCCESS = "FETCH_ALL_COURSES_SUCCESS";
export const FETCH_ALL_COURSES_FAILURE = "FETCH_ALL_COURSES_FAILURE";
export const SET_RECENT_COURSES = "SET_RECENT_COURSES";
export const SET_NEWEST_COURSES = "SET_NEWEST_COURSES";
//GET INSTRUCTORS
export const FETCH_INSTRUCTORS_REQUEST = "FETCH_INSTRUCTORS_REQUEST";
export const FETCH_INSTRUCTORS_SUCCESS = "FETCH_INSTRUCTORS_SUCCESS";
export const FETCH_INSTRUCTORS_FAILURE = "FETCH_INSTRUCTORS_FAILURE";
export const GET_INSTRUCTOR_BY_ID_REQUEST = "GET_INSTRUCTOR_BY_ID_REQUEST";
export const GET_INSTRUCTOR_BY_ID_SUCCESS = "GET_INSTRUCTOR_BY_ID_SUCCESS";
export const GET_INSTRUCTOR_BY_ID_FAILURE = "GET_INSTRUCTOR_BY_ID_FAILURE";

//SEARCH INSTRUCTORS
export const SEARCH_INSTRUCTORS_REQUEST = "SEARCH_INSTRUCTORS_REQUEST";
export const SEARCH_INSTRUCTORS_SUCCESS = "SEARCH_INSTRUCTORS_SUCCESS";
export const SEARCH_INSTRUCTORS_FAILURE = "SEARCH_INSTRUCTORS_FAILURE";

//SEARCH COURSES
export const SEARCH_COURSES_REQUEST = "SEARCH_COURSES_REQUEST";
export const SEARCH_COURSES_SUCCESS = "SEARCH_COURSES_SUCCESS";
export const SEARCH_COURSES_FAILURE = "SEARCH_COURSES_FAILURE";

//GET CERTIFICATES
export const FETCH_CERTIFICATES_REQUEST = "FETCH_CERTIFICATES_REQUEST";
export const FETCH_CERTIFICATES_SUCCESS = "FETCH_CERTIFICATES_SUCCESS";
export const FETCH_CERTIFICATES_FAILURE = "FETCH_CERTIFICATES_FAILURE";

//DELETE CERTIFICATES
export const DELETE_CERTIFICATES_REQUEST = "DELETE_CERTIFICATES_REQUEST";
export const DELETE_CERTIFICATES_SUCCESS = "DELETE_CERTIFICATES_SUCCESS";
export const DELETE_CERTIFICATES_FAILURE = "FETCH_CERTIFICATES_FAILURE";

//GET NEWS
//GET CERTIFICATES
export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";
//ADD NEW CERTIFICATE
export const ADD_NEW_CERTIFICATES_REQUEST = "ADD_NEW_CERTIFICATES_REQUEST";
export const ADD_NEW_CERTIFICATES_SUCCESS = "ADD_NEW_CERTIFICATES_SUCCESS";
export const ADD_NEW_CERTIFICATES_FAILURE = "ADD_NEW_CERTIFICATES_FAILURE";

//GET REVIEWS
export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAILURE = "FETCH_REVIEWS_FAILURE";

//GET OURBLOG
export const FETCH_OURBLOG_REQUEST = "FETCH_OURBLOG_REQUEST";
export const FETCH_OURBLOG_SUCCESS = "FETCH_OURBLOG_SUCCESS";
export const FETCH_OURBLOG_FAILURE = "FETCH_OURBLOG_FAILURE";

//GET STATEMENTS
export const FETCH_STATEMENTS_REQUEST = "FETCH_STATEMENTS_REQUEST";
export const FETCH_STATEMENTS_SUCCESS = "FETCH_STATEMENTS_SUCCESS";
export const FETCH_STATEMENTS_FAILURE = "FETCH_STATEMENTS_FAILURE";

//SEARCH REVIEW
export const SEARCH_REVIEWS_REQUEST = "SEARCH_REVIEW_REQUEST";
export const SEARCH_REVIEWS_SUCCESS = "SEARCH_REVIEW_SUCCESS";
export const SEARCH_REVIEWS_FAILURE = "SEARCH_REVIEW_FAILURE";

//UPDATE PROFILE
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

//CREATE COURSE
export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAILURE = "CREATE_COURSE_FAILURE";


// DELETE SAVED  COURSES
export const DELETE_SAVED_COURSES_REQUEST = "DELETE_SAVED_COURSES_REQUEST";
export const DELETE_SAVED_COURSES_SUCCESS = "DELETE_SAVED_COURSES_SUCCESS";
export const DELETE_SAVED_COURSES_FAILURE = "DELETE_SAVED_COURSES_FAILURE";

//ADD SAVED COURSES
export const ADD_SAVED_COURSES_REQUEST = "ADD_SAVED_COURSES_REQUEST";
export const ADD_SAVED_COURSES_SUCCESS = "ADD_SAVED_COURSES_SUCCESS";
export const ADD_SAVED_COURSES_FAILURE = "ADD_SAVED_COURSES_FAILURE";

// GET SAVED COURSES
export const FETCH_SAVED_COURSES_REQUEST = "FETCH_SAVED_COURSES_REQUEST";
export const FETCH_SAVED_COURSES_SUCCESS = "FETCH_SAVED_COURSES_SUCCESS";
export const FETCH_SAVED_COURSES_FAILURE = "FETCH_SAVED_COURSES_FAILURE";


//GET EARNING
export const FETCH_EARNING_REQUEST = "FETCH_EARNING_REQUEST";
export const FETCH_EARNING_SUCCESS = "FETCH_EARNING_SUCCESS";
export const FETCH_EARNING_FAILURE = "FETCH_EARNING_FAILURE";
//Get VERIFICATION
export const VERIFY_COURSE_SUCCESS = 'VERIFY_COURSE_SUCCESS';
export const VERIFY_COURSE_FAILURE = 'VERIFY_COURSE_FAILURE';

// GET SHOPPING COURSES
export const FETCH_SHOPPING_COURSES_REQUEST = "FETCH_SHOPPING_COURSES_REQUEST";
export const FETCH_SHOPPING_COURSES_SUCCESS = "FETCH_SHOPPING_COURSES_SUCCESS";
export const FETCH_SHOPPING_COURSES_FAILURE = "FETCH_SHOPPING_COURSES_FAILURE";

//ADD SHOPPING COURSES
export const ADD_SHOPPING_COURSES_REQUEST = "ADD_SHOPPING_COURSES_REQUEST";
export const ADD_SHOPPING_COURSES_SUCCESS = "ADD_SHOPPING_COURSES_SUCCESS";
export const ADD_SHOPPING_COURSES_FAILURE = "ADD_SHOPPING_COURSES_FAILURE";


// DELETE SHOPPING  COURSES
export const DELETE_SHOPPING_COURSES_REQUEST = "DELETE_SHOPPING_COURSES_REQUEST";
export const DELETE_SHOPPING_COURSES_SUCCESS = "DELETE_SHOPPING_COURSES_SUCCESS";
export const DELETE_SHOPPING_COURSES_FAILURE = "DELETE_SHOPPING_COURSES_FAILURE";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const SET_MESSAGES = "SET_MESSAGES";
export const MESSAGE_LOADING = "MESSAGE_LOADING";
export const MESSAGE_ERROR = "MESSAGE_ERROR";


export const FETCH_ANALYSIS_REQUEST = 'FETCH_ANALYSIS_REQUEST';
export const FETCH_ANALYSIS_SUCCESS = 'FETCH_ANALYSIS_SUCCESS';
export const FETCH_ANALYSIS_FAILURE = 'FETCH_ANALYSIS_FAILURE';

// GET INVOICE
export const FETCH_INVOICE_REQUEST = 'FETCH_INVOICE_REQUEST';
export const FETCH_INVOICE_SUCCESS = 'FETCH_INVOICE_SUCCESS';
export const FETCH_INVOICE_FAILURE = 'FETCH_INVOICE_FAILURE';